# specs_2024.py
from __future__ import annotations

from .specs import TableSpec, NarrSpec
from .parsers import (
    parse_triple_table,
    parse_numbered_yesno,
    parse_numbered_dual_tokens,
    parse_1c7_pha,
    parse_2a5_bed_coverage,
)

# -------------------------
# TABLE SPECS (simple tables)
# -------------------------
TABLE_SPECS_2024: list[TableSpec] = [

    # ----- 1B-1 triple table -----
    TableSpec(
        key="df_1b1",
        start=[
            r"^\s*1B[-–]1\.\s*Inclusive\s+Structure\s+and\s+Participation.*?$",
            r"\bInclusive Structure and Participation\b",
        ],
        stop=[
            r"^\s*1B[-–]1a\.",
            r"^\s*1B[-–]2\.",
            r"^\s*1C[-–]1\.",
            r"^\s*2A[-–]1\.",
        ],
        parser=parse_triple_table,
        safety_pages_ahead=3,
    ),

    # ----- 1C tables -----
    TableSpec("df_1c1",
        start=[r"^\s*1C[-–]1\.\s?.*$", r"\b1C[-–]1\.\b"],
        stop=[r"^\s*1C[-–]2\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=3,
    ),
    TableSpec("df_1c2",
        start=[r"^\s*1C[-–]2\.\s?.*$", r"\b1C[-–]2\.\b"],
        stop=[r"^\s*1C[-–]3\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),
    TableSpec("df_1c3",
        start=[r"^\s*1C[-–]3\.\s?.*$", r"\b1C[-–]3\.\b"],
        stop=[r"^\s*1C[-–]4\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1c4_basic",
        start=[r"^\s*1C[-–]4\.\s?.*$", r"\b1C[-–]4\.\b"],
        stop=[
            r"^\s*1C[-–]5\.",
            r"^\s*1C\.\s*Coordination\s+and\s+Engagement",
            r"^\s*1C[-–]1\.",
            r"^\s*1D[-–]1\.",
            r"^\s*2A[-–]1\.",
        ],
        parser=parse_numbered_yesno,
        safety_pages_ahead=3,
    ),
    TableSpec("df_1c4c",
        start=[r"^\s*1C[-–]4\.\s?.*$", r"\b1C[-–]4\.\b"],
        stop=[
            r"^\s*1C[-–]5\.",
            r"^\s*1C\.\s*Coordination\s+and\s+Engagement",
            r"^\s*1C[-–]1\.",
            r"^\s*1D[-–]1\.",
            r"^\s*2A[-–]1\.",
        ],
        parser=lambda lines: parse_numbered_dual_tokens(lines, suffixes=("mou", "oth")),
        safety_pages_ahead=3,
    ),

    TableSpec("df_1c5_basic",
        start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=3,
    ),
    TableSpec("df_1c5c",
        start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=lambda lines: parse_numbered_dual_tokens(lines, suffixes=("proj", "ces")),
        safety_pages_ahead=3,
    ),

    TableSpec("df_1c6",
        start=[
            r"^\s*1C[-–]6\.\s*Addressing\s+the\s+Needs\s+of\s+Lesbian,\s*Gay,\s*Bisexual,\s*Transgender\s+and\s+Queer\+.*$",
            r"^\s*1C[-–]6\.\s*",
        ],
        stop=[
            r"^\s*1C[-–]6a\.",
            r"^\s*1C[-–]7\.",
            r"^\s*[1I]D[-–]1\.",
            r"^\s*2A[-–]1\.",
        ],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1c7",
        start=[
            r"^\s*1C[-–]7\.\s*Public\s+Housing\s+Agencies\s+within\s+Your\s+CoC",
            r"^\s*1C[-–]7\.\s*",
        ],
        stop=[
            r"^\s*1C[-–]7a\.",
            r"^\s*1D[-–]1\.",
            r"^\s*2A[-–]1\.",
        ],
        parser=parse_1c7_pha,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1c7b",
        start=[
            r"^\s*1C[-–]7b\.\s*Moving\s+On\s+Strategy\s+with\s+Affordable\s+Housing\s+Providers.*$",
            r"^\s*1C[-–]7b\.\s*",
        ],
        stop=[r"^\s*1C[-–]7c\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1c7c",
        start=[
            r"^\s*1C[-–]7c\.\s*Include\s+Units\s+from\s+PHA\s+Administered\s+Programs.*$",
            r"^\s*1C[-–]7c\.\s*",
        ],
        stop=[r"^\s*1C[-–]7d\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    # ----- 1D tables -----
    TableSpec("df_1d1",
        start=[
            r"^\s*1D[-–]1\.\s*Preventing\s+People\s+Transitioning\s+from\s+Public\s+Systems\s+from\s+Experiencing\s+Homelessness.*$",
            r"^\s*1D[-–]1\.\s*",
        ],
        stop=[r"^\s*1D[-–]2\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1d4",
        start=[
            r"^\s*[1I]D[-–]4\.\s*Strategies\s+to\s+Prevent\s+Criminalization\s+of\s+Homelessness.*$",
            r"^\s*[1I]D[-–]4\.\s*",
        ],
        stop=[r"^\s*[1I]D[-–]5\.", r"^\s*[1I]D[-–]6\.", r"^\s*2A[-–]1\."],
        parser=lambda lines: parse_numbered_dual_tokens(lines, suffixes=("engaged", "implemented")),
        safety_pages_ahead=2,
    ),

    TableSpec("df_1d6",
        start=[
            r"^\s*[1I]D[-–]6\.\s*Mainstream\s+Benefits[-–]\s*CoC\s+Annual\s+Training\s+of\s+Project\s+Staff.*$",
            r"^\s*[1I]D[-–]6\.\s*",
        ],
        stop=[r"^\s*[1I]D[-–]6a\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=2,
    ),

    TableSpec("df_1d9b",
        start=[r"^\s*[1I]D[-–]9b\.\s*"],
        stop=[r"^\s*[1I]D[-–]9c\.", r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        parser=parse_numbered_yesno,
        safety_pages_ahead=4,
    ),

        # ----- 2A tables -----
    TableSpec("df_2a5",
        start=[r"^\s*2A[-–]5\.\s*Bed Coverage Rate"],
        stop=[
            r"^\s*2A[-–]5a\.",
            r"^\s*2A[-–]6\.",
            r"^\s*2B[-–]1\.",
        ],
        parser=parse_2a5_bed_coverage,
        safety_pages_ahead=2,
    ),
]


# -------------------------
# NARRATIVE SPECS
# -------------------------
NARR_SPECS_2024: list[NarrSpec] = [

    # ----- 1B narratives -----
    NarrSpec(
        key="narr_1b1a",
        anchor_start=[
            r"^\s*1B[-–]1a\.\s*Experience\s+Promoting\s+Racial\s+Equity.*$",
            r"^\s*1B[-–]1a\.\s*",
        ],
        anchor_stop=[r"^\s*1B[-–]1b\.", r"^\s*1B[-–]2\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^NOFO\s+Section\s+III\.B\.3\.c\.", r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1B[-–]1b\.", r"^\s*1B[-–]2\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1b2",
        anchor_start=[r"^\s*1B[-–]2\.\s*Open\s+Invitation\s+for\s+New\s+Members.*$", r"^\s*1B[-–]2\.\s*"],
        anchor_stop=[r"^\s*1B[-–]3\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^NOFO\s+Section\s+V\.B\.1\.a\.\(2\)", r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1B[-–]3\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1b3",
        anchor_start=[r"^\s*1B[-–]3\.\s*CoC['’]s\s+Strategy\s+to\s+Solicit/Consider\s+Opinions.*$", r"^\s*1B[-–]3\.\s*"],
        anchor_stop=[r"^\s*1B[-–]4\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^NOFO\s+Section\s+V\.B\.1\.a\.\(3\)", r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1B[-–]4\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1b4",
        anchor_start=[r"^\s*1B[-–]4\.\s*Public\s+Notification\s+for\s+Proposals.*$", r"^\s*1B[-–]4\.\s*"],
        anchor_stop=[r"^\s*1B[-–]5\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^NOFO\s+Section\s+V\.B\.1\.a\.\(4\)", r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1B[-–]5\.", r"^\s*1C[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),

    # ----- 1C narratives -----
    NarrSpec(
        key="narr_1c4a",
        anchor_start=[r"^\s*1C[-–]4\.\s?.*$", r"\b1C[-–]4\.\b"],
        anchor_stop=[r"^\s*1C[-–]5\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below\s+the\s+formal\s+partnerships.*$"],
        narr_stop=[r"^\s*(?:1C|C)[-–]4b\.", r"^\s*1C[-–]5\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c4b",
        anchor_start=[r"^\s*1C[-–]4\.\s?.*$", r"\b1C[-–]4\.\b"],
        anchor_stop=[r"^\s*1C[-–]5\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[
            r"^\s*(?:1C|C)[-–]4b\.\s*Informing\s+Individuals\s+and\s+Families.*$",
            r"^Describe\s+in\s+the\s+field\s+below\s+written\s+policies.*$",
        ],
        narr_stop=[r"^\s*(?:1C|C)[-–]4c\.", r"^\s*1C[-–]5\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c5a",
        anchor_start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        anchor_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[
            r"^\s*1C[-–]?5a\.\s*Collaborating\s+with\s+Federally\s+Funded\s+Programs.*$",
            r"^Describe\s+in\s+the\s+field\s+below\s+how\s+your\s+CoC\s+regularly\s+collaborates.*$",
        ],
        narr_stop=[r"^\s*1C[-–]?5b\.", r"^\s*1C[-–]?5c\.", r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c5b",
        anchor_start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        anchor_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[
            r"^\s*1C[-–]?5b\.\s*Implemented\s+Safety\s+Planning.*$",
            r"^Describe\s+in\s+the\s+field\s+below\s+how\s+your\s+CoC['’]s\s+coordinated\s+entry.*$",
        ],
        narr_stop=[r"^\s*1C[-–]?5c\.", r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c5d",
        anchor_start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        anchor_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^\s*1C[-–]?5d\.\s*Implemented\s+VAWA-Required.*$", r"^Describe\s+in\s+the\s+field\s+below:.*$"],
        narr_stop=[r"^\s*1C[-–]?5e\.\s", r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_5e",
        anchor_start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        anchor_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^\s*1C[-–]5e\.\s", r"^Facilitating\s+Safe\s+Access\s+to\s+Housing.*"],
        narr_stop=[r"^\s*1C[-–]5f\.\s", r"^Identifying\s+and\s+Removing\s+Barriers.*", r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_5f",
        anchor_start=[r"^\s*1C[-–]5\.\s?.*$", r"\b1C[-–]5\.\b"],
        anchor_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^\s*1C[-–]5f\.\s", r"^Identifying\s+and\s+Removing\s+Barriers.*"],
        narr_stop=[r"^\s*1C[-–]6\.", r"^\s*1D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c6a",
        anchor_start=[r"^\s*1C[-–]6a\.\s*Anti-Discrimination\s+Policy.*$", r"^\s*1C[-–]6a\.\s*"],
        anchor_stop=[r"^\s*1C[-–]7\.", r"^\s*[1I]D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1C[-–]7\.", r"^\s*[1I]D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec(
        key="narr_1c7a",
        anchor_start=[r"^\s*1C[-–]7a\.\s*Written\s+Policies\s+on\s+Homeless\s+Admission\s+Preferences.*$", r"^\s*1C[-–]7a\.\s*"],
        anchor_stop=[r"^\s*1C[-–]7b\.", r"^\s*1C[-–]7c\.", r"^\s*[1I]D[-–]1\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*1C[-–]7b\.", r"^\s*1C[-–]7c\.", r"^\s*[1I]D[-–]1\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),

    # ----- 1D narratives (the “simple” ones) -----
    NarrSpec("narr_1d2a",
        anchor_start=[r"^\s*[1I]D[-–]2a\.\s*Project\s+Evaluation\s+for\s+Housing\s+First\s+Compliance.*$", r"^\s*[1I]D[-–]2a\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]3\.", r"^\s*[1I]D[-–]4\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]3\.", r"^\s*[1I]D[-–]4\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d3",
        anchor_start=[r"^\s*[1I]D[-–]3\.\s*Street\s+Outreach.*$", r"^\s*[1I]D[-–]3\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]4\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]4\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d6a",
        anchor_start=[r"^\s*[1I]D[-–]6a\.\s*Information\s+and\s+Training\s+on\s+Mainstream\s+Benefits.*$", r"^\s*[1I]D[-–]6a\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]7\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]7\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d7",
        anchor_start=[r"^\s*[1I]D[-–]7\.\s*Partnerships\s+with\s+Public\s+Health\s+Agencies.*$", r"^\s*ID[-–]7\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]7a\.", r"^\s*ID[-–]7a\.", r"^\s*[1I]D[-–]8\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]7a\.", r"^\s*[1I]D[-–]8\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d7a",
        anchor_start=[r"^\s*[1I]D[-–]7a\.\s*Collaboration\s+With\s+Public\s+Health\s+Agencies.*$", r"^\s*ID[-–]7a\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]8\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]8\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d8",
        anchor_start=[r"^\s*[1I]D[-–]8\.\s*Coordinated\s+Entry\s+Standard\s+Processes.*$", r"^\s*ID[-–]8\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]8a\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]8a\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d8a",
        anchor_start=[r"^\s*[1I]D[-–]8a\.\s*Coordinated\s+Entry[-–]Program\s+Participant-Centered\s+Approach.*$", r"^\s*ID[-–]8a\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]8b\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]8b\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d8b",
        anchor_start=[r"^\s*[1I]D[-–]8b\.\s*Coordinated\s+Entry[-–]Informing\s+Program\s+Participants.*$", r"^\s*ID[-–]8b\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]9\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]9\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),

    NarrSpec("narr_1d9a",
        anchor_start=[r"^\s*[1I]D[-–]9a\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]9b\.", r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]9b\.", r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d9c",
        anchor_start=[r"^\s*[1I]D[-–]9c\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]9d\.", r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]9d\.", r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d9d",
        anchor_start=[r"^\s*[1I]D[-–]9d\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]10\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),

    # 1D-10, 1D-10b, 1D-10c, 1D-11 are still “simple narrative blocks”
    NarrSpec("narr_1d10",
        anchor_start=[r"^\s*[1I]D[-–]10\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]10a\.", r"^\s*2A[-–]1\."],
        narr_start=[r"Describe\s+in\s+the\s+field\s+below"],
        narr_stop=[r"^\s*[1I]D[-–]10a\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=3,
    ),
    NarrSpec("narr_1d10b",
        anchor_start=[r"^\s*[1I]D[-–]10b\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]10c\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]10c\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=2,
    ),
    NarrSpec("narr_1d10c",
        anchor_start=[r"^\s*[1I]D[-–]10c\.\s*"],
        anchor_stop=[r"^\s*[1I]D[-–]11\.", r"^\s*2A[-–]1\."],
        narr_start=[r"^Describe\s+in\s+the\s+field\s+below.*$"],
        narr_stop=[r"^\s*[1I]D[-–]11\.", r"^\s*2A[-–]1\."],
        safety_pages_ahead=2,
    ),
    NarrSpec("val_1d11",
        anchor_start=[r"^\s*[1I]D[-–]11\.\s*"],
        anchor_stop=[r"^\s*1E[-–]1\.", r"^\s*1E\."],
        narr_start=[r"Describe\s+in\s+the\s+field\s+below"],
        narr_stop=[r"^\s*1E[-–]1\.", r"^\s*1E\."],
        safety_pages_ahead=3,
    ),
        # ----- 2A narratives -----
    NarrSpec(
        key="narr_2a_4",
        anchor_start=[
            r"^\s*2A[-–]4\.\s*Comparable Databases for DV Providers",
            r"^\s*2A[-–]4\.\s*",
        ],
        anchor_stop=[r"^\s*2A[-–]5\."],
        narr_start=[r"Describe\s+in\s+the\s+field\s+below", r"limit\s*2,?500\s*characters"],
        narr_stop=[r"^\s*2A[-–]5\."],
        safety_pages_ahead=3,
    ),

    NarrSpec(
        key="narr_2a_5a",
        anchor_start=[
            r"^\s*2A[-–]5a\.\s*Partial Credit for Bed Coverage",
            r"^\s*2A[-–]5a\.\s*",
        ],
        anchor_stop=[r"^\s*2A[-–]6\.", r"^\s*2B[-–]1\."],
        narr_start=[r"Describe\s*:" , r"describe\s*:"],
        narr_stop=[r"^\s*2A[-–]6\.", r"^\s*2B[-–]1\."],
        safety_pages_ahead=2,
    ),

    # ----- 2B narratives -----
    NarrSpec(
        key="narr_2b_3",
        anchor_start=[
            r"^\s*2B[-–]3\.\s*PIT Count",
            r"^\s*2B[-–]3\.\s*",
        ],
        anchor_stop=[
            r"^\s*2B[-–]4\.",
            r"^\s*2C[-–]1\.",
            r"^\s*3A[-–]1\.",
        ],
        narr_start=[
            r"Describe\s+in\s+the\s+field\s+below",
            r"limit\s*2,?500\s*characters",
        ],
        narr_stop=[
            r"^\s*2B[-–]4\.",
            r"^\s*2C[-–]1\.",
            r"^\s*3A[-–]1\.",
        ],
        safety_pages_ahead=3,
    ),

]
